version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"  # Liên kết cổng của container với cổng máy chủ
    volumes:
      - ./workspace:/workspace  # Gắn kết thư mục để lưu trữ mã và dữ liệu

