FROM mysql
MAINTAINER anhbn3@gmail.com

ENV MYSQL_ROOT_PASSWORD abc13579
ENV MYSQL_DATABASE demo
ENV MYSQL_USER     test
ENV MYSQL_PASSWORD test123
RUN apt-get update && apt-get install -y apt-utils && apt-get upgrade -y && apt-get install vim -y && apt install net-tools -y && apt-get install telnet -y

EXPOSE 3306
